export const BTN_CLICK_SUCCESS = 'BTN_CLICK_SUCCESS';
export const BTN_CLICK_REQUEST = 'BTN_CLICK_REQUEST';
export const BTN_CLICK_FAILURE = 'BTN_CLICK_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
